[versions]
kotlin = "2.0.21"
kotlinx-coroutines = "1.7.3"

plasmovoice = "2.1.5"
pv-gradle-plugin = "1.0.4-SNAPSHOT"
run-paper = "2.3.1"

[libraries]
plasmovoice = { module = "su.plo.voice.api:server", version.ref = "plasmovoice" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }

[plugins]
pv-entrypoints = { id = "su.plo.voice.plugin.entrypoints", version.ref = "pv-gradle-plugin" }
pv-kotlin-relocate = { id = "su.plo.voice.plugin.relocate-kotlin", version.ref = "pv-gradle-plugin" }
pv-java-templates = { id = "su.plo.voice.plugin.java-templates", version.ref = "pv-gradle-plugin" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
